name: openfuelfr
description: A client for https://www.prix-carburants.gouv.fr/rubrique/opendata/
version: 1.1.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  logging: ^1.0.2
  test: ^1.20.1
dependencies: 
  archive: ^3.2.1
  dio: ^4.0.4
  html: ^0.15.0
  maps_toolkit: ^2.0.0
  xml: ^5.3.1
